### ISSUE TITLE
tv_chart_rails

### ISSUE THREAD

**Issue by nosenko86** [mualucky/tv_chart_rails#1]
Hi Bob! i would like to ask you about tv_chart_rails, correct me if wrong, i can use tv_chart_rails without logo tradingview, without datafeed tradingview, with my logo on my website with mine datafeed?

**Comment by mualucky** [comment]
sorry, all right reserved by https://www.tradingview.com/, you can ask them about this. But I think you should not change the logo, even with your own datafeed.
